# For global module specific settings.

[github]
token = "GITHUBTOKEN"

[modules.serverstatus]
default = "default"

[serverstatus]
default = "default"
servername = "default"
type = "ss13"

[nudge]
password = "secret"

#[serverstatus.default]
#type = "ss13"
#default = "guitt"

#[modules.serverstatus.default]
#type = "ss13"
